# Generated by Django 4.1.3 on 2022-12-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stock_holding_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_info',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
